baseURL = "https://markbirger.com"
languageCode = "en-us"
title = "Mark Birger"
theme = "cactus"
copyright = "Mark Birger"
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
publishDir = "docs"

# summaryLength = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  description = "Senior Software Engineer from Prague."

  logo = "/images/logo.gif"

  colortheme = "white" # dark, light, white, or classic
  # rss = true # generate rss feed. default value is false
  # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list
  defaultProjectsLanguage = "en"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/kusha"
    action = "star my projects on"
  # [[params.social]]
  #   name = "twitter"
  #   link = "https://twitter.com/kusha1"
  [[params.social]]
    name = "linkedin"
    link = "https://cz.linkedin.com/in/mark-birger"
    action = "connect on"
  [[params.social]]
    name = "telegram-plane"
    link = "https://t.me/markkusha"
    action = "contact me via"
  # [[params.social]]
  #   name = "email"
  #   link = "example@example.com"  # no need for "mailto:" in the head

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writings"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
